<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp7.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoreServicePayment.Domain\CoreServicePayment.Domain.csproj" />
    <ProjectReference Include="..\CoreServicePayment.Database\CoreServicePayment.Database.csproj" />
  </ItemGroup>


</Project>
