# How execute file:
# docker-compose -f databases.yaml up -d
name: ldap.compose

networks:
  my-network:
   driver: bridge

services:
  openlap:
    hostname: openldap
    image: bitnami/openldap:latest
    restart: always
    ports:
      - 1389:1389
      - 1636:1636
    environment:
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: adminpassword
      LDAP_USERS: user01,user02
      LDAP_PASSWORDS: password1,password2
      LDAP_ROOT: dc=example,dc=org
      LDAP_ADMIN_DN: cn=admin,dc=example,dc=org
    networks:
     - my-network
    volumes:
      - db-data:/var/lib/openldap/data  

  maria-database:
    hostname: mariadb
    image: bitnami/mariadb-galera:latest    
    restart: always
    ports:
     - 3306:3306    
    environment:
     MARIADB_ROOT_PASSWORD: root-password
     MARIADB_GALERA_MARIABACKUP_PASSWORD: backup-password
     MARIADB_USER: customuser
     MARIADB_DATABASE: customdatabase
    #  MARIADB_ENABLE_LDAP: yes
    #  LDAP_URI: ldap://openldap:1389
    #  LDAP_BASE: dc=example,dc=org
    #  LDAP_BIND_DN: cn=admin,dc=example,dc=org
    #  LDAP_BIND_PASSWORD: adminpassword
    networks:
     - my-network     
    volumes:
      - db-data:/var/lib/maria/data  
  
  #Test Connection Mariana - OpenLdap
  # docker run -it --rm --name mariadb-client \
  #   --network my-network \
  #   bitnami/mariadb-galera:latest mysql -h mariadb-galera -u customuser -D customdatabase -pcustompassword
volumes:
  db-data:
    driver: local